name: Deploy

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.6'
      
      - name: Install build deps
        run: npm i
        
      - name: Build
        run: npm run build
        
      - name: Prune build deps
        run: npm prune --production
      
      - name: Deploy
        run: npm run serve
